### ISSUE TITLE
list time entries from new to old

### ISSUE THREAD

**Issue by foss-** [te-online/timemanager#172] opened 2024-04-23 12:31 UTC
The way Time entries are displayed is inconsistent. When selecting `Time entries` from left side panel the entries are shown from `New to Old`.

But when selecting a time entry and TimeManager shows all time entries for a specific Client, Project and Task the time entries are shown `Old to New`.

As any interaction will likely happen with more recent tasks and interest of users about listed tasks also will likely be with more recent entries, it list the entries from `New to Old` in that view as well. Would also make for a more consistent UX.

**Comment by te-online** [comment] 2024-04-24 18:34
Hey, thanks for opening this issue 😊 

I think this is a duplicate of #25

**Closed by te-online** 2024-04-24 18:34 UTC

**Comment by foss-** [comment] 2024-04-24 18:37
Sorry, not sure how I missed that 😵‍💫
