### ISSUE TITLE
Move time entries to different tasks and projects

### ISSUE THREAD

**Issue by 31SFX4** [te-online/timemanager#147] opened 2023-11-22 10:58 UTC
It should be possible to move a completed time entry to a different task. 

Sometimes I add a time entry from the task view (so the task is filled in automatically) and then realise that I was in the wrong task and the entry should refer to a different task. At present I have to delete it (after writing down the times) and recreate it, but it would be better if it was possible to change the task in the time entry edit dialog, or have some other mechanism to move the entry to a different task.

**Comment by te-online** [comment] 2023-11-23 22:26
Great idea 😊 Guess, it's a duplicate of https://github.com/te-online/timemanager/issues/61

**Closed by te-online** 2023-11-23 22:26 UTC
Labels: duplicate
