### ISSUE TITLE
Feature request: Moving entries, tasks, projects

### ISSUE THREAD

**Issue by gerhardbeck** [te-online/timemanager#140] opened 2023-09-21 18:36 UTC
I would find it great if you could move time entries from one task to another, even in another project.
The same would be with moving tasks from project to project or projects from customer to customer
In my work sometimes I need to change it often.

**Comment by te-online** [comment] 2023-09-21 19:40
Hey 👋  Thanks for your suggestion – sounds nice. It looks like a duplicate of this #61 – let's merge these.

**Closed by te-online** 2023-09-21 19:40 UTC

**Comment by gerhardbeck** [comment] 2023-09-21 20:14
oh, sorry, didn't saw it
