### ISSUE TITLE
Missing clients in the android app

### ISSUE THREAD

**Issue by aligator** [te-online/timemanager#150] opened 2023-12-14 20:26 UTC
Hi, 

I somehow have the problem that since one of the last updates the android app is missing some clients.
In the web it exists.

Not really sure what is happening, I cannot see a difference between the clients in the db...

If you need more specific information, please tell me.

I think this is related to https://github.com/te-online/timemanager/issues/148

Clearing the app data and reconnecting does not help.

**Comment by te-online** [comment] 2023-12-14 23:42
Yes, I think you might be onto something there 🤔  I will look into this a bit more as soon as I can – so sorry it broke 😢 I really need to get an Android phone to test...

**Comment by te-online** [comment] 2023-12-15 00:02
Update: I think I have identified the issues and will be pushing a fix in the coming days. Hang in there 🙏

**Comment by te-online** [comment] 2023-12-17 16:02
@aligator Please check out release 0.3.11, which hopefully concludes the saga of Android app sync API bugs 🙏 😊

**Comment by aligator** [comment] 2023-12-21 15:04
Thank you! The first tests of my users were successfull😃

**Comment by Xeladaren** [comment] 2023-12-21 19:42
Hi,

I start to use Timemanager on my nextcloud server since few days, but the Android apps never work. I don't know if the problem is this issue, another, or just my config. But when I try to update on the app, I have nothing appear on the Android App, and I have this log line on my nextcloud console : 
```
192.168.1.1 - Xeladaren [21/Dec/2023:19:37:23 +0000] "POST //index.php/apps/timemanager/api/updateObjects HTTP/1.1" 500 5203 "-" "Dart/2.15 (dart:io)"
```

And I have the logs details on these files :
[Timemanager_log_raw.json](https://github.com/te-online/timemanager/files/13745632/Timemanager_log_raw.json)
[Timemanager_log_formated.txt](https://github.com/te-online/timemanager/files/13745633/Timemanager_log_formated.txt)

And if I create some items on the Android apps, only the `Client` object appears on the Web interface.

If my problem is not an issue of the app, but my configs, I apologize for this post and If you have any information about it, I really appreciate.

**Comment by te-online** [comment] 2023-12-21 20:20
@Xeladaren  Hm ... This looks strange. It seems like your database thinks the values for the `IN( ... )` expression in the query are columns? What database and which version are you using? 😊

**Comment by Xeladaren** [comment] 2023-12-21 20:38
I use Nextcloud 28.0.0, on a Postgres Database 16.1-1, all in Dockers Images.

**Comment by te-online** [comment] 2023-12-22 13:27
Okay, I think this may be a Postgres issue, because it seems to use `'` single quotes instead of `"` double quotes to limit values in an `IN` expression. However, this is confusing, because it was just like that before 🤔 But I can't imagine no-one else using Postgres, so I'm surprise you're the first one to report :D 

I will look into it, give me a few days.

**Comment by Xeladaren** [comment] 2023-12-22 13:38
Yes, take your time, I use my nextcloud and timemanager only for personal use and I don't plane to log anything before next year. so it is not urgent.

**Comment by te-online** [comment] 2024-01-04 09:53
Short update: This could be a Postgres issue, similar to #152.

I have yet to get my development environment to work with Postgres, then I can reproduce and fix the issue. Apologies.

**Comment by te-online** [comment] 2024-01-21 22:04
It took me hours to set-up the dev environment with postgres and a couple minutes to fix the query. Classic 😂 

This fix will be in the next version 🙏 You can expect it released in the upcoming weeks. Sorry for the long wait!

**Closed by te-online** 2024-01-21 22:04 UTC
