### ISSUE TITLE
Dashboard/Task entry: allow creating new tasks on the fly

### ISSUE THREAD

**Issue by raph-topo** [te-online/timemanager#178] opened 2024-06-03 18:32 UTC
Regarding the add new time entry form, which is sleek and efficient already (good job!).

Currently, a new time entry has you go through the following steps in order (particularly when keyboard navigating with tab as I guess was designed for): description, duration, start time, end time, and finally task.

Only when you notice at that point that the appropriate task does not yet exist, you have to browse to Client/Project & add a task; then come back to dashboard, reload page so that the task appears in drop-down, and type everything again. That might happen dozens of times a day when working on many different projects.

I see two possible solutions:

- load the tasks autocomplete via XHR at each typing (would allow to create a new task in a new tab, without loosing what's been previously typed; but that's not a self-explaining solution)
- allow creating tasks on the fly in that box (much better, but probably complex to double out the way it works in each separate page already)
- put the tasks dropdown in front of the form so that one sees if a task is missing before having typed anything else in (simplest & most efficient for user, since it then shows hierarchically left to right client-project-task-description)

**Comment by te-online** [comment] 2024-06-04 19:31
Duplicate of #120

**Comment by te-online** [comment] 2024-06-04 19:31
Good points 👍 Let's continue the conversation over at #102

**Closed by te-online** 2024-06-04 19:31 UTC
